{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(request_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by(method) (rate(request_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Authentication Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(authAttempt_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Revenue / Min (BTC)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzaRevenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "description": "Unique users that are logged in and have made an http request in the last 10 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "activeUsers_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Pizza Purchases / Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizzasSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(pizzaFailures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "endpointLatency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "endpoint latency"
    }
   ]
  },
  {
   "title": "Pizza Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "pizzaLatency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "pizza latency"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  }
 ]
}